dataset:
  type: CityScapesDataset
  data_dir: ./data/cityscapes_ss/
  size: [512, 1024]
  loader:
    batch_size: 16
    num_workers: 4

model:
  type: BiSeNetV1
  backbone:
    type: ResNet
    depth: 18

optimizer:
  type: SGD
  lr: 0.025
  momentum: 0.9
  weight_decay: 0.0005

scheduler:
  type: PolynomialLR
  max_iterations: 40000
  power: 0.9
  warmup_iterations: 1000

runtime:
  epochs: 216
