dataset:
  type: CityScapesDataset
  data_dir: ./data/cityscapes_ss/
  size: [512, 1024]
  loader:
    batch_size: 4
    num_workers: 4

model:
  type: SegFormer
  scale: b2

optimizer:
  type: AdamW
  lr: 0.0006
  betas: [0.9, 0.999]
  weight_decay: 0.01

scheduler:
  type: PolynomialLR
  max_iterations: 160000
  power: 0.9
  min_lr: 0.0000001

runtime:
  epochs: 217

testtime:
  ms_flip: true
