dataset:
  type: CityScapesDataset
  data_dir: ./data/cityscapes_ss/
  size: [512, 1024]
  loader:
    batch_size: 4
    num_workers: 4

model:
  type: SegFormer
  backbone:
    type: MixTransformer
    scale: b2
    pretrain: ./assets/mit_b2.pth

optimizer:
  type: AdamW
  lr: 0.0006
  betas: [0.9, 0.999]
  weight_decay: 0.01

scheduler:
  type: PolynomialLR
  max_iterations: 160000
  power: 1.0
  min_lr: 0.0
  warmup_iterations: 1500
  warmup_ratio: 0.000001

runtime:
  epochs: 216
