dataset:
  type: CityScapesDataset
  data_dir: ./data/cityscapes_ss/
  size: [512, 1024]
  loader:
    batch_size: 8
    num_workers: 4

model:
  type: UNet

optimizer:
  type: SGD
  lr: 0.025
  momentum: 0.9
  weight_decay: 0.0005

scheduler:
  type: PolynomialLR
  max_iterations: 80000
  power: 0.9
  min_lr: 0.0000001

runtime:
  epochs: 217
