dataset:
  type: CityScapesDataset
  data_dir: ./data/cityscapes_ss/
  size: [512, 1024]
  loader:
    batch_size: 3
    num_workers: 2

model:
  type: UNet
  channels: 64

optimizer:
  type: SGD
  lr: 0.025
  momentum: 0.9
  weight_decay: 0.0005

scheduler:
  type: PolynomialLR
  max_iterations: 40000
  power: 0.9

runtime:
  epochs: 109
